### ISSUE TITLE
environmentaid: NPE

### ISSUE THREAD

**Issue by SRLJustin** [xKylee/plugins-source#289]
```
2021-01-16 17:44:28 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.reflect.InvocationTargetException
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:83)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay3.PublishRelay$PublishDisposable.onNext(PublishRelay.java:179)
	at com.jakewharton.rxrelay3.PublishRelay.accept(PublishRelay.java:144)
	at com.jakewharton.rxrelay3.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:115)
	at net.runelite.client.callback.Hooks.post(Hooks.java:175)
	at he.broadcastHidden(Widget.java:422)
	at he.onHiddenChanged(Widget.java:483)
	at he.t(Widget.java:495)
	at ab.x(class41.java:205)
	at ai.ji(WorldMapManager.java:9477)
	at client.jd(Client.java:9447)
	at client.he(Client.java:6028)
	at client.fw(Client.java:2997)
	at client.ak(Client.java:1256)
	at bd.aj(GameShell.java:351)
	at bd.run(GameShell.java:330)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.runelite.client.plugins.Plugin.lambda$findSubscriptions$1(Plugin.java:102)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
	at net.runelite.client.plugins.environmentaid.EnvironmentAidPlugin.widgetEvent(EnvironmentAidPlugin.java:216)
	... 26 common frames omitted
	```

**Comment by andrewterra** [comment]
I'd suggest turning this plugin off until you're going to use it, toggling it on and off when the widget is actually on the screen works for me.
