### ISSUE TITLE
mesex

### ISSUE THREAD

**Issue by Crystalknoct** [xKylee/plugins-source#30]
2020-03-05 08:24:16 [AWT-EventQueue-0] WARN n.r.c.plugins.config.PluginListPanel - Error when starting plugin MenuEntrySwapperExtendedPlugin
net.runelite.client.plugins.PluginInstantiationException: java.lang.NullPointerException
at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:469)
at net.runelite.client.plugins.config.PluginListPanel.startPlugin(PluginListPanel.java:429)
at net.runelite.client.plugins.config.PluginListItem.lambda$new$2(PluginListItem.java:152)
at java.desktop/javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:1995)
at java.desktop/javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2315)
at java.desktop/javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:458)
at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:364)
at java.desktop/javax.swing.AbstractButton.setSelected(AbstractButton.java:341)
at net.runelite.client.plugins.config.PluginListItem.setPluginEnabled(PluginListItem.java:199)
at net.runelite.client.plugins.config.PluginListPanel.lambda$refresh$9(PluginListPanel.java:293)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at net.runelite.client.plugins.config.PluginListPanel.refresh(PluginListPanel.java:288)
at net.runelite.client.plugins.config.PluginListPanel.rebuildPluginList(PluginListPanel.java:276)
at net.runelite.client.plugins.config.ConfigPlugin.startUp(ConfigPlugin.java:113)
at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:447)
at net.runelite.client.plugins.PluginManager.lambda$startPlugins$2(PluginManager.java:288)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: null
at net.runelite.client.plugins.menuentryswapperextended.MenuEntrySwapperExtendedPlugin.rcSwaps(MenuEntrySwapperExtendedPlugin.java:444)
at net.runelite.client.plugins.menuentryswapperextended.MenuEntrySwapperExtendedPlugin.startUp(MenuEntrySwapperExtendedPlugin.java:228)
at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:447)
... 28 common frames omitted

**Comment by xKylee** [comment]
fixed in #33
